name: attribute_localizations
description: Attribute localizations.
version: 1.0.0
author: moaidalrazhy
homepage: https://github.com/OTF-7/flutter-localizations/packages/attribute_localizations

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
