name: validation_localizations
description: Validation localizations.
version: 1.0.0
author: moaidalrazhy
homepage: https://github.com/OTF-7/flutter-localizations

publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  attribute_localizations:
    git:
      url: https://github.com/OTF-7/flutter-localizations.git
      path: packages/attribute_localizations

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
